import asyncio
import os
import re
from typing import Union
import yt_dlp
from pyrogram.enums import MessageEntityType
from pyrogram.types import Message
from py_yt import VideosSearch, Playlist

DOWNLOAD_DIR = "downloads"
MAX_CACHED_FILES = 500  # ဖိုင်အရေအတွက် အများဆုံး ၅၀၀ ထိသာ သိမ်းမည်


YOUTUBE_COOKIE_STRING = os.environ.get("YouTube_Cookie", "# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.youtube.com  TRUE  /  TRUE  1788834227  VISITOR_PRIVACY_METADATA  CgJNTRIEGgAgZg%3D%3D
.youtube.com  TRUE  /  TRUE  1807842226  __Secure-3PSID  g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXounGOWJraQeCKpqG-oSwq9wACgYKAZkSARISFQHGX2MizRsEjWIBfOf8FT3Y3LMa_RoVAUF8yKpOPp3cWUdYQ5Ao5O96IuJM0076
.youtube.com  TRUE  /  TRUE  1773283987  GPS  1
.youtube.com  TRUE  /  FALSE  1804818233  SIDCC  AKEyXzW1sqaKu6ScKuu9DKvRXkDOUkGb35L6HhIlYENKXlnQKqsd44MpPeDXCEVNXNiXMxq4
.youtube.com  TRUE  /  TRUE  1773368661  YSC  V5xhbUOi2aM
.youtube.com  TRUE  /  FALSE  1807842226  SID  g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXoYEH2e75zTffKW0Xjy7JjNAACgYKAYYSARISFQHGX2Miw6hqbohoy53Wf7whYiki9xoVAUF8yKqy6CRK8cS9icqdLlHz7eND0076
.youtube.com  TRUE  /  TRUE  1804818226  __Secure-1PSIDTS  sidts-CjUBBj1CYnb_2un-x8U3DosdFcqPYVJhbg8Bk68ZCnIivIxZ-HGzJjNZhZ3mKsTTKPb9rfqcrxAA
.youtube.com  TRUE  /  TRUE  1773282831  CONSISTENCY  AG2Tqf8zG-huG-xjZAla2JPHKiMEKIrXDCYwlOHHGuhn4BqYzEQeeWHU4KBqrAnF4gXzuExsDwlRUzVRXKDOoYbqs5Cc2zhXioJl1PDof9f5T3qYUl27a9fnzomuUSXtDrxnp1hPZjCN1LI5o2cd_BCb
.youtube.com  TRUE  /  TRUE  1807842226  SAPISID  ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com  TRUE  /  TRUE  1804818233  __Secure-1PSIDCC  AKEyXzWE3s3Z4jjWsZL2ADVxRV8QrrovXNLf3fLjfD9yjEGzPH3nS1nBe6mDRNa_Z19OZUfKZw
.youtube.com  TRUE  /  TRUE  1807842226  SSID  AT0hp-hXDaolbHwv7
.youtube.com  TRUE  /  TRUE  1807842226  __Secure-1PAPISID  ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com  TRUE  /  TRUE  1807842226  __Secure-1PSID  g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXo1xo64CJRyhnVfADBa2PqOgACgYKAV0SARISFQHGX2Mi1ad7QdhlGEysEgNracH2bhoVAUF8yKreHDECH5KvXV8UNvE31fIb0076
.youtube.com  TRUE  /  TRUE  1807842226  __Secure-3PAPISID  ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com  TRUE  /  TRUE  1804818233  __Secure-3PSIDCC  AKEyXzUDsCV5ZzeaZ8_RRuemevoTvbJutsmPMlGkA6CmKMPY1zz4f5-mKS5HuYiYODFDpNNRRg
.youtube.com  TRUE  /  TRUE  1804818226  __Secure-3PSIDTS  sidts-CjUBBj1CYnb_2un-x8U3DosdFcqPYVJhbg8Bk68ZCnIivIxZ-HGzJjNZhZ3mKsTTKPb9rfqcrxAA
.youtube.com  TRUE  /  TRUE  1788834187  __Secure-YNID  16.YT=GlwsbGn0fwwI-d-fno4xNR8ODUrXPmpXzVPd0Yw-YqCAZRTG2HLiCB6OPx_wu7cH-QOOa2ymy52RM-yS5A3yX2uA8Dp09uFhXKuV7krGSttP2UxmiC8yLsmvqa3Koezzs8cgbS5HZA8hQw6hVBJNPumr8rBZqjn0ehTKVK53mbtKU3iIf96Cquwc-hHR71SIqwN0TiSUPz3iQcwSl59oahyvxBQJrswqogCv1UEvAKwHWO9pQVvPhI7yj19BukJzfaYdJpxM8__eI0Ixp97WheNpkhT5n_qZm6xu_Go9dmMGTglnchyztzIzxRy0iS7SBky383yf7gUUuQTjcFvwCQ
.youtube.com  TRUE  /  FALSE  1807842226  APISID  r2h8dJdwnPtOnB6w/A696rI3lpsRhDG7gE
.youtube.com  TRUE  /  FALSE  1807842226  HSID  AKFaV2VhVw1F0A1Ki
.youtube.com  TRUE  /  TRUE  1807842227  LOGIN_INFO  AFmmF2swRAIgcB7wcOs4WNVu-ntf7mqpZ0eDodNht4tOYj9GjX_22kcCIDZ6go5sU7AJYiXaiXvDo7RTNDux2DRqDwi5aMYf_6dA:QUQ3MjNmd2RNVmZwS2M4ajJCX0NDQTZRLUhZUERGOVU3ekR3UWpkZVZ3QXVwZ1JEWmM5cDExQWV4MzRzaXF5bS1uY0dFTUlDcDJySkVkd3pZbFRVc29uSEtKT0tscDRDOG93c3Zxd0R1ZkZCTlBYcGdqaFVzMWhhOTZaRWlwTDF6WDJWU0tiM3FmRW05dUlkMlVndFROblhyejBxeGc2a09R
.youtube.com  TRUE  /  TRUE  1807842230  PREF  tz=Asia.Rangoon&f7=100&f4=4000000
.youtube.com  TRUE  /  TRUE  1788834227  VISITOR_INFO1_LIVE  rQRaTxG5Dg8 ")

def get_cookie_file():
    """Cookie စာသားကို Temporary cookies.txt ဖိုင်အဖြစ် ပြောင်းလဲပေးခြင်း"""
    if not YOUTUBE_COOKIE_STRING:
        return None
    cookie_path = "temp_cookies.txt"
    try:
        with open(cookie_path, "w", encoding="utf-8") as f:
            f.write(YOUTUBE_COOKIE_STRING)
        return cookie_path
    except Exception:
        return None

def clean_old_files():
    """downloads/ ထဲတွင် ဖိုင် ၅၀၀ ပြည့်ပါက အဟောင်းများကို အလိုအလျောက်ဖျက်မည်"""
    if not os.path.exists(DOWNLOAD_DIR):
        return
    
    files = [os.path.join(DOWNLOAD_DIR, f) for f in os.listdir(DOWNLOAD_DIR)]
    files.sort(key=os.path.getmtime)
    
    while len(files) >= MAX_CACHED_FILES:
        oldest_file = files.pop(0)
        try:
            if os.path.exists(oldest_file):
                os.remove(oldest_file)
        except Exception:
            pass

def time_to_seconds(time):
    stringt = str(time)
    return sum(int(x) * 60 ** i for i, x in enumerate(reversed(stringt.split(":"))))


async def download_song(link: str) -> str:
    video_id = link.split("v=")[-1].split("&")[0] if "v=" in link else link
    if not video_id or len(video_id) < 3:
        return None

    os.makedirs(DOWNLOAD_DIR, exist_ok=True)
    file_path = os.path.join(DOWNLOAD_DIR, f"{video_id}.mp3")
    
    # Caching စစ်ဆေးခြင်း - ရှိပြီးသားဆိုရင် ချက်ချင်းပြန်ယူမည်
    if os.path.exists(file_path) and os.path.getsize(file_path) > 0:
        return file_path

    clean_old_files()
    cookie_file = get_cookie_file()

    try:
        ydl_opts = {
            "format": "bestaudio[ext=m4a]/bestaudio/best",
            "outtmpl": os.path.join(DOWNLOAD_DIR, f"{video_id}.%(ext)s"),
            "geo_bypass": True,
            "nocheckcertificate": True,
            "quiet": True,
            "postprocessors": [
                {
                    "key": "FFmpegExtractAudio",
                    "preferredcodec": "mp3",
                    "preferredquality": "192",
                }
            ],
        }
        
        if cookie_file and os.path.exists(cookie_file):
            ydl_opts["cookiefile"] = cookie_file

        loop = asyncio.get_running_loop()
        def run_ytdl():
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([link])

        await loop.run_in_executor(None, run_ytdl)

        if cookie_file and os.path.exists(cookie_file):
            try:
                os.remove(cookie_file)
            except:
                pass

        if os.path.exists(file_path) and os.path.getsize(file_path) > 0:
            return file_path
        return None
    except Exception as e:
        print(f"Direct Download Song Error: {e}")
        if cookie_file and os.path.exists(cookie_file):
            try:
                os.remove(cookie_file)
            except:
                pass
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
            except Exception:
                pass
        return None


async def download_video(link: str) -> str:
    video_id = link.split("v=")[-1].split("&")[0] if "v=" in link else link
    if not video_id or len(video_id) < 3:
        return None

    os.makedirs(DOWNLOAD_DIR, exist_ok=True)
    file_path = os.path.join(DOWNLOAD_DIR, f"{video_id}.mp4")
    
    # Caching စစ်ဆေးခြင်း
    if os.path.exists(file_path) and os.path.getsize(file_path) > 0:
        return file_path

    clean_old_files()
    cookie_file = get_cookie_file()

    try:
        ydl_opts = {
            "format": "best[ext=mp4]/best",
            "outtmpl": os.path.join(DOWNLOAD_DIR, f"{video_id}.%(ext)s"),
            "geo_bypass": True,
            "nocheckcertificate": True,
            "quiet": True,
        }

        if cookie_file and os.path.exists(cookie_file):
            ydl_opts["cookiefile"] = cookie_file

        loop = asyncio.get_running_loop()
        def run_ytdl():
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([link])

        await loop.run_in_executor(None, run_ytdl)

        if cookie_file and os.path.exists(cookie_file):
            try:
                os.remove(cookie_file)
            except:
                pass

        if os.path.exists(file_path) and os.path.getsize(file_path) > 0:
            return file_path
        return None
    except Exception as e:
        print(f"Direct Download Video Error: {e}")
        if cookie_file and os.path.exists(cookie_file):
            try:
                os.remove(cookie_file)
            except:
                pass
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
            except Exception:
                pass
        return None


class YouTubeAPI:
    def __init__(self):
        self.base = "https://www.youtube.com/watch?v="
        self.regex = r"(?:youtube\.com|youtu\.be)"
        self.status = "https://www.youtube.com/oembed?url="
        self.listbase = "https://youtube.com/playlist?list="
        self.reg = re.compile(r"\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])")

    async def exists(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        return bool(re.search(self.regex, link))

    async def url(self, message_1: Message) -> Union[str, None]:
        messages = [message_1]
        if message_1.reply_to_message:
            messages.append(message_1.reply_to_message)
        for message in messages:
            if message.entities:
                for entity in message.entities:
                    if entity.type == MessageEntityType.URL:
                        text = message.text or message.caption
                        return text[entity.offset: entity.offset + entity.length]
            elif message.caption_entities:
                for entity in message.caption_entities:
                    if entity.type == MessageEntityType.TEXT_LINK:
                        return entity.url
        return None

    async def details(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            title = result["title"]
            duration_min = result["duration"]
            thumbnail = result["thumbnails"][0]["url"].split("?")[0]
            vidid = result["id"]
            duration_sec = int(time_to_seconds(duration_min)) if duration_min else 0
        return title, duration_min, duration_sec, thumbnail, vidid

    async def title(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            return result["title"]

    async def duration(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            return result["duration"]

    async def thumbnail(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            return result["thumbnails"][0]["url"].split("?")[0]

    async def video(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        try:
            downloaded_file = await download_video(link)
            if downloaded_file:
                return 1, downloaded_file
            return 0, "Video download failed"
        except Exception as e:
            return 0, f"Video download error: {e}"

    async def playlist(self, link, limit, user_id, videoid: Union[bool, str] = None):
        if videoid:
            link = self.listbase + link
        if "&" in link:
            link = link.split("&")[0]
        try:
            plist = await Playlist.get(link)
        except Exception:
            return []
        videos = plist.get("videos") or []
        ids = []
        for data in videos[:limit]:
            if not data:
                continue
            vid = data.get("id")
            if not vid:
                continue
            ids.append(vid)
        return ids

    async def track(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            title = result["title"]
            duration_min = result["duration"]
            vidid = result["id"]
            yturl = result["link"]
            thumbnail = result["thumbnails"][0]["url"].split("?")[0]
        track_details = {
            "title": title,
            "link": yturl,
            "vidid": vidid,
            "duration_min": duration_min,
            "thumb": thumbnail,
        }
        return track_details, vidid

    async def formats(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        ytdl_opts = {"quiet": True}
        ydl = yt_dlp.YoutubeDL(ytdl_opts)
        with ydl:
            formats_available = []
            r = ydl.extract_info(link, download=False)
            for format in r["formats"]:
                try:
                    if "dash" not in str(format["format"]).lower():
                        formats_available.append(
                            {
                                "format": format["format"],
                                "filesize": format.get("filesize"),
                                "format_id": format["format_id"],
                                "ext": format["ext"],
                                "format_note": format["format_note"],
                                "yturl": link,
                            }
                        )
                except Exception:
                    continue
        return formats_available, link

    async def slider(self, link: str, query_type: int, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        a = VideosSearch(link, limit=10)
        result = (await a.next()).get("result")
        title = result[query_type]["title"]
        duration_min = result[query_type]["duration"]
        vidid = result[query_type]["id"]
        thumbnail = result[query_type]["thumbnails"][0]["url"].split("?")[0]
        return title, duration_min, thumbnail, vidid

    async def download(
        self,
        link: str,
        mystic,
        video: Union[bool, str] = None,
        videoid: Union[bool, str] = None,
        songaudio: Union[bool, str] = None,
        songvideo: Union[bool, str] = None,
        format_id: Union[bool, str] = None,
        title: Union[bool, str] = None,
    ) -> str:
        if videoid:
            link = self.base + link
        try:
            if video:
                downloaded_file = await download_video(link)
            else:
                downloaded_file = await download_song(link)
            if downloaded_file:
                return downloaded_file, True
            return None, False
        except Exception:
            return None, False


YouTube = YouTubeAPI()
